/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.*;
import MODELO.Estudiante;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EMERSON ALBORNOZ
 */
public class EstudianteGUI extends javax.swing.JDialog {

    /**
     * Creates new form EstudianteGUI
     */
    Grupo gru;
    DefaultTableModel modelo;

    public EstudianteGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);  //Centrar ventana
        gru = new Grupo("341");
        cargarDatos();
        modelo = gru.cargarDatosParaJTable();
        jTextField1_Nro_Estudiantes_.setText(gru.estudiantes.size() + "");
        jTable1.setModel(modelo);
    }

    public void cargarDatos() {
        gru.estudiantes = TransaccEst.cargar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_Nro_Estudiantes_ = new javax.swing.JTextField();
        jButton_Regresar_ = new javax.swing.JButton();
        jButton1_ADD_ = new javax.swing.JButton();
        jButton1_MOD_ = new javax.swing.JButton();
        jButton1_DEL_ = new javax.swing.JButton();
        jButton1_Buscar_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_Identificacion_ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_Nombre_ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Email_ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_DirectorioFoto_ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1_NombreFoto_ = new javax.swing.JTextField();
        jButton1_cambiarIMG_ = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1_Apellido_ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/5.png"))); // NOI18N
        jLabel7.setText("ADMINISTRADOR DE ESTUDIANTES");

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel7)
                .addGap(167, 167, 167)
                .addComponent(jLabel15)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PreceseUnClick(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 560, 110));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel5.setText("Numero de estudiantes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        jTextField1_Nro_Estudiantes_.setEditable(false);
        jTextField1_Nro_Estudiantes_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1_Nro_Estudiantes_.setText("0");
        jTextField1_Nro_Estudiantes_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Nro_Estudiantes_ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_Nro_Estudiantes_, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 30, -1));

        jButton_Regresar_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton_Regresar_.setText("Regresar");
        jButton_Regresar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Regresar_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Regresar_, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, -1, -1));

        jButton1_ADD_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton1_ADD_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Agregar.png"))); // NOI18N
        jButton1_ADD_.setText("Adicionar");
        jButton1_ADD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ADD_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_ADD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 140, 50));

        jButton1_MOD_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton1_MOD_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Modificar.png"))); // NOI18N
        jButton1_MOD_.setText("Modificar");
        jButton1_MOD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_MOD_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_MOD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 140, 50));

        jButton1_DEL_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton1_DEL_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Eliminar.png"))); // NOI18N
        jButton1_DEL_.setText("Borrar");
        jButton1_DEL_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_DEL_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_DEL_, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 130, 50));

        jButton1_Buscar_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton1_Buscar_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Buscar.png"))); // NOI18N
        jButton1_Buscar_.setText("Buscar");
        jButton1_Buscar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_Buscar_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_Buscar_, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, 50));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel1.setText("Identificacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 30));

        jTextField1_Identificacion_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Identificacion_ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_Identificacion_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jTextField1_Nombre_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Nombre_ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_Nombre_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 210, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));
        jPanel1.add(jTextField1_Email_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel8.setText("Directorio foto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jTextField1_DirectorioFoto_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_DirectorioFoto_ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_DirectorioFoto_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 210, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel9.setText("Nombre foto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));
        jPanel1.add(jTextField1_NombreFoto_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, -1));

        jButton1_cambiarIMG_.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jButton1_cambiarIMG_.setText("Cambiar img");
        jButton1_cambiarIMG_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_cambiarIMG_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1_cambiarIMG_, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 100, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/4.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 90));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 140, 120));

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel10.setText("Foto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jTextField1_Apellido_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_Apellido_ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_Apellido_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 210, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 13)); // NOI18N
        jLabel6.setText("Sexo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("M");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("F");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Regresar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Regresar_ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_Regresar_ActionPerformed

    private void jTextField1_Identificacion_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Identificacion_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Identificacion_ActionPerformed

    private void jTextField1_Apellido_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Apellido_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Apellido_ActionPerformed

    private void jTextField1_Nombre_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Nombre_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Nombre_ActionPerformed

    private void jButton1_MOD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_MOD_ActionPerformed
        // TODO add your handling code here:
        int idEst = 0;
        String nombre = "";
        String apellido = "";
        char sexo = ' ';
        String email = "";
        String dirRuta = "";
        String foto = "";
        //variable de ayuda para hacer la captura de las cadenas 
        String sidEst = "";
        //-------------------------------------------------------
        sidEst = jTextField1_Identificacion_.getText();
        idEst = Integer.parseInt(sidEst);
        apellido = jTextField1_Apellido_.getText();
        nombre = jTextField1_Nombre_.getText();
        if (jRadioButton1.isSelected()) {
            sexo = 'M';
        } else {
            sexo = 'F';
        }
        email = jTextField1_Email_.getText();
        dirRuta = jTextField1_DirectorioFoto_.getText();
        foto = jTextField1_NombreFoto_.getText();
        Estudiante x = new Estudiante(idEst, apellido, nombre, sexo, email, dirRuta, foto);
        if (gru.modificar(x) == true) {
            modelo = gru.cargarDatosParaJTable();
            jTextField1_Nro_Estudiantes_.setText(gru.estudiantes.size() + "");
            jTable1.setModel(modelo);
            mostrarMensaje("Se modificó con éxito");
        } else {
            mostrarMensaje("No se modificó, problablemente no exista el usuario");
        }
    }//GEN-LAST:event_jButton1_MOD_ActionPerformed

    private void jButton1_DEL_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_DEL_ActionPerformed
        // TODO add your handling code here:
        int idEst = 0;
        String sidEst = "";
        sidEst = jTextField1_Identificacion_.getText();
        idEst = Integer.parseInt(sidEst);
        if (gru.eliminar(idEst)) {
            modelo = gru.cargarDatosParaJTable();
            jTextField1_Nro_Estudiantes_.setText(gru.estudiantes.size() + "");
            jTable1.setModel(modelo);
            mostrarMensaje("Se eliminó con éxito");
        } else {
            mostrarMensaje("No se pudo eliminar, pueda que no exista el usuario");
        }
    }//GEN-LAST:event_jButton1_DEL_ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1_Nro_Estudiantes_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_Nro_Estudiantes_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_Nro_Estudiantes_ActionPerformed

    private void jButton1_ADD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ADD_ActionPerformed
        // TODO add your handling code here:
        int idEst = 0;
        String nombre = "";
        String apellido = "";
        char sexo = ' ';
        String email = "";
        String dirRuta = "";
        String foto = "";
        //variable de ayuda para hacer la captura de las cadenas 
        String sidEst = "";
        //-------------------------------------------------------
        sidEst = jTextField1_Identificacion_.getText();
        if (!Utilidades.esEntero(sidEst)) {
            mostrarMensaje("El codigo está mal escrito o tiene caracteres diferentes a enteros");
            return;
        }
        idEst = Integer.parseInt(sidEst);
        apellido = jTextField1_Apellido_.getText();
        if (!Utilidades.sonsoloLetras(apellido)) {
            mostrarMensaje("El campo de apellido está mal escrito");
            return;
        }
        nombre = jTextField1_Nombre_.getText();
        if (!Utilidades.sonsoloLetras(nombre)) {
            mostrarMensaje("El campo de nombre está mal escrito");
            return;
        }
        if (jRadioButton1.isSelected()) {
            sexo = 'M';
        } else {
            sexo = 'F';
        }
        email = jTextField1_Email_.getText();
        if (!Utilidades.esEmailvalido(email)) {
            mostrarMensaje("El campo de email está mal escrito");
            return;
        }
        dirRuta = jTextField1_DirectorioFoto_.getText();
        foto = jTextField1_NombreFoto_.getText();
        Estudiante x = new Estudiante(idEst, apellido, nombre, sexo, email, dirRuta, foto);
        if (gru.add(x) == true) {
            modelo = gru.cargarDatosParaJTable();  //Se vuelve a cargar el modelo para que actualizen los datos de la tabla
            jTextField1_Nro_Estudiantes_.setText(gru.estudiantes.size() + "");  //Se actualiza el numero de estudiantes
            jTable1.setModel(modelo);
            mostrarMensaje("Se adicionó con éxito");
        } else {
            mostrarMensaje("No se adicionó, puede que ya exista");
        }
    }//GEN-LAST:event_jButton1_ADD_ActionPerformed

    private void jButton1_Buscar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_Buscar_ActionPerformed
        // TODO add your handling code here:
        int idEst = 0;
        String sidEst = "";
        sidEst = jTextField1_Identificacion_.getText();
        idEst = Integer.parseInt(sidEst);
        Estudiante x = gru.buscar(idEst);
        if (x != null) {
            moverAlaVentana(x);
            cargarFoto(x.getDirRuta(), x.getFoto());
        } else {
            mostrarMensaje("No se encontró, pueda que no exista el usuario");
        }
    }//GEN-LAST:event_jButton1_Buscar_ActionPerformed
    public void cargarFoto(String ruta, String foto) {
        //String dirRutaFoto = ruta + foto + ".JPG"
        String dirRutaFoto = ruta + foto + ".JPG";
        javax.swing.ImageIcon iconfoto = new javax.swing.ImageIcon(dirRutaFoto);
        // jlabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/100.JPG")));
        if (iconfoto.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE) {
            jLabel11.setText("");
            jLabel11.setIcon(iconfoto); //Se pone en el jlabel
        } else {
            dirRutaFoto = ruta + "nofoto.JPG";
            iconfoto = new javax.swing.ImageIcon(dirRutaFoto);
            jLabel11.setText("");
            jLabel11.setIcon(iconfoto); //Se pone en el jlabel 
        }
    }
    private void PreceseUnClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PreceseUnClick
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();     //Seleccionar fila
        int col = jTable1.getSelectedColumn();   //Seleccionar columna

        String dato = (String) jTable1.getValueAt(fila, 0);
        int idest = Integer.parseInt(dato);
        Estudiante x = gru.buscar(idest);
        if (x != null) {
            moverAlaVentana(x);
        }
    }//GEN-LAST:event_PreceseUnClick

    private void jTextField1_DirectorioFoto_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_DirectorioFoto_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_DirectorioFoto_ActionPerformed

    private void jButton1_cambiarIMG_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_cambiarIMG_ActionPerformed
        // TODO add your handling code here:

        JFileChooser jf = new JFileChooser();
        jf.setMultiSelectionEnabled(false);   //Para que el usuario sólo pueda hacer una elección.
        if (jf.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {    //Validar si la imagen a sido seleccionada
            //rsdragdropfiles.RSDragDropFiles.setCopiar(jf.getSelectedFile().toString(), "src/VISTA.Imagenes/nofoto.jpg");
            jLabel12.setIcon(new ImageIcon(jf.getSelectedFile().toString()));
        }

    }//GEN-LAST:event_jButton1_cambiarIMG_ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jLabel15MouseClicked
    public void moverAlaVentana(Estudiante x) {
        jTextField1_Identificacion_.setText(Integer.toString(x.getIdEst()));
        jTextField1_Apellido_.setText(x.getApellido());
        jTextField1_Nombre_.setText(x.getNombre());
        if (x.getSexo() == 'M') {
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton2.setSelected(true);
        }
        jTextField1_Email_.setText(x.getEmail());
        jTextField1_DirectorioFoto_.setText(x.getDirRuta());
        jTextField1_NombreFoto_.setText(x.getFoto());
    }

    public void mostrarMensaje(String m) {
        javax.swing.JOptionPane.showMessageDialog(this, m);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                EstudianteGUI dialog = new EstudianteGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_ADD_;
    private javax.swing.JButton jButton1_Buscar_;
    private javax.swing.JButton jButton1_DEL_;
    private javax.swing.JButton jButton1_MOD_;
    private javax.swing.JButton jButton1_cambiarIMG_;
    private javax.swing.JButton jButton_Regresar_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_Apellido_;
    private javax.swing.JTextField jTextField1_DirectorioFoto_;
    private javax.swing.JTextField jTextField1_Email_;
    private javax.swing.JTextField jTextField1_Identificacion_;
    private javax.swing.JTextField jTextField1_NombreFoto_;
    private javax.swing.JTextField jTextField1_Nombre_;
    private javax.swing.JTextField jTextField1_Nro_Estudiantes_;
    // End of variables declaration//GEN-END:variables
}
