/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.*;
import MODELO.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EMERSON ALBORNOZ
 */

public class NotasGUI extends javax.swing.JDialog {

    /**
     * Creates new form NotasGUI
     */
    Grupo gru;
    Calculos cal;
    DefaultTableModel modelo;
    public NotasGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //this.setUndecorated(true);  //Para eliminar la barra de la ventana
        initComponents();
        this.setLocationRelativeTo(this);   //Centrar la ventana
        gru = new Grupo("341A");
        cargarDatos();
        cal = new Calculos();
        modelo = gru.cargarDatosNotasParaJTable();
        jTable1.setModel(modelo);
        deshabilitarBotones();
    }
    public void cargarDatos(){
        gru.notas = TransaccNota.cargar();
    }
    public void habilitarBotones(){
        jButton2_ADD_.setEnabled(true);
        jButton3_DEL_.setEnabled(true);
        jButton4_BuscarPorIdNota_.setEnabled(true);
        jButton5_MOD_.setEnabled(true);
    }
    
    public void deshabilitarBotones(){
        jButton2_ADD_.setEnabled(false);
        jButton3_DEL_.setEnabled(false);
        jButton4_BuscarPorIdNota_.setEnabled(false);
        jButton5_MOD_.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1_BUSCAR_ = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_IdEst_ = new javax.swing.JTextField();
        jTextField2_APELLIDO_ = new javax.swing.JTextField();
        jTextField3_NOMBRE_ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4_IDNOTA_ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5_IDEST_ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6_TIPO_ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7_VALOR_ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8_PORCENTAJE_ = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField9_CORTE_ = new javax.swing.JTextField();
        jButton2_ADD_ = new javax.swing.JButton();
        jButton3_DEL_ = new javax.swing.JButton();
        jButton4_BuscarPorIdNota_ = new javax.swing.JButton();
        jButton5_MOD_ = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1_promedio_ = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3_Definitiva_ = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4_porcentaje2_ = new javax.swing.JTextField();
        jTextField5_cantidadQyT_ = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1_BUSCAR_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Buscar.png"))); // NOI18N
        jButton1_BUSCAR_.setText("Buscar");
        jButton1_BUSCAR_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BUSCAR_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1_BUSCAR_, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 120, -1));

        jLabel1.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel2.add(jTextField1_IdEst_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, -1));

        jTextField2_APELLIDO_.setEditable(false);
        jPanel2.add(jTextField2_APELLIDO_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 190, -1));

        jTextField3_NOMBRE_.setEditable(false);
        jPanel2.add(jTextField3_NOMBRE_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 30));

        jLabel2.setText("Foto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 30, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel3.setText("Id Nota");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 40, -1));

        jTextField4_IDNOTA_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4_IDNOTA_ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4_IDNOTA_, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel4.setText("Id Estudiante");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
        jPanel2.add(jTextField5_IDEST_, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 60, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel5.setText("Tipo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));
        jPanel2.add(jTextField6_TIPO_, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 50, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel6.setText("Valor");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));
        jPanel2.add(jTextField7_VALOR_, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 50, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel7.setText("Porcentaje");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));
        jPanel2.add(jTextField8_PORCENTAJE_, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 70, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel8.setText("Corte");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jTextField9_CORTE_.setEditable(false);
        jTextField9_CORTE_.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField9_CORTE_.setText("1");
        jPanel2.add(jTextField9_CORTE_, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 40));

        jButton2_ADD_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Agregar.png"))); // NOI18N
        jButton2_ADD_.setText("Adicionar");
        jButton2_ADD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ADD_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2_ADD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton3_DEL_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Eliminar.png"))); // NOI18N
        jButton3_DEL_.setText("Borrar");
        jButton3_DEL_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_DEL_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3_DEL_, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jButton4_BuscarPorIdNota_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Buscar.png"))); // NOI18N
        jButton4_BuscarPorIdNota_.setText("Buscar por idNota");
        jButton4_BuscarPorIdNota_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_BuscarPorIdNota_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4_BuscarPorIdNota_, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 170, -1));

        jButton5_MOD_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/Modificar.png"))); // NOI18N
        jButton5_MOD_.setText("Modificar");
        jButton5_MOD_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_MOD_ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5_MOD_, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jButton6.setText("Regresar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel9.setText("Cantidad de Q y T");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel10.setText("Porcentaje");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, -1, -1));

        jLabel11.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel11.setText("Nota definitiva del corte");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, -1, -1));
        jPanel2.add(jTextField1_promedio_, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 130, -1));

        jTextField2.setText("30%");
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 50, -1));
        jPanel2.add(jTextField3_Definitiva_, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 529, 90));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/4.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel13.setText("Porcentaje");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextField4_porcentaje2_.setEditable(false);
        jPanel2.add(jTextField4_porcentaje2_, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, -1));
        jPanel2.add(jTextField5_cantidadQyT_, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, -1));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Imagenes/5.png"))); // NOI18N
        jLabel14.setText("ADMINISTRADOR DE ESTUDIANTES");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Corbel", 1, 15)); // NOI18N
        jLabel15.setText("X");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 50));

        jLabel16.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel16.setText("Estudiante");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel17.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel17.setText("Apellido");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel18.setFont(new java.awt.Font("Corbel", 0, 13)); // NOI18N
        jLabel18.setText("Promedio Quizes y Talleres");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_BUSCAR_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BUSCAR_ActionPerformed
        // TODO add your handling code here:
        String sidest = jTextField1_IdEst_.getText();
        int idestx = Integer.parseInt(sidest);
        buscarEyMoverE(idestx);
        Nota r = (Nota) gru.notas.get(0);
        cal.calcularPromedioYCantQT(idestx);
        moverCalculos();
        moverAlaVentana(r);
        
    }//GEN-LAST:event_jButton1_BUSCAR_ActionPerformed
    public void buscarEyMoverE(int idestx){
        Estudiante x = TransaccEst.buscar(idestx);
        if (x != null) {
            jTextField2_APELLIDO_.setText(x.getApellido());
            jTextField3_NOMBRE_.setText(x.getNombre());
            cargarFoto(x.getDirRuta(), x.getFoto());
            gru.notas = TransaccNota.cargarNotaEstudiante(idestx);
            modelo = gru.cargarDatosNotasParaJTable();
            jTable1.setModel(modelo);
            habilitarBotones();
        }
        else{
            mostrarMensaje("NO SE ENCONTRÓ EL ESTUDIANTE");
        }
    }
    public void moverAlaVentana(Nota x){
        jTextField4_IDNOTA_.setText(Integer.toString(x.getIdNota()));
        jTextField5_IDEST_.setText(Integer.toString(x.getIdEst()));
        jTextField9_CORTE_.setText(Integer.toString(x.getCorte()));
        jTextField6_TIPO_.setText(Character.toString(x.getTipo()));
        jTextField7_VALOR_.setText(Double.toString(x.getValor()));
        jTextField8_PORCENTAJE_.setText(Double.toString(x.getPorcentaje()));
        
    }
    public void blanquearDatos(){
        jTextField4_IDNOTA_.setText("");
        jTextField1_IdEst_.setText("");
        jTextField9_CORTE_.setText("");
        jTextField6_TIPO_.setText("");
        jTextField7_VALOR_.setText("");
        jTextField8_PORCENTAJE_.setText("");
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4_BuscarPorIdNota_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_BuscarPorIdNota_ActionPerformed
        // TODO add your handling code here:
        String sidnotax = jTextField4_IDNOTA_.getText();
        int idnotax = Integer.parseInt(sidnotax);
        Nota no = gru.buscarNota(idnotax);
        if (no != null) {
            moverAlaVentana(no);
            buscarEyMoverE(no.getIdEst());
        }
        else{
            mostrarMensaje("Esa nota no existe");
        }
    }//GEN-LAST:event_jButton4_BuscarPorIdNota_ActionPerformed

    private void jButton3_DEL_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_DEL_ActionPerformed
        // TODO add your handling code here:
        String sidnotax = jTextField4_IDNOTA_.getText();
        int idnotax = Integer.parseInt(sidnotax);
        if (gru.eliminarNota(idnotax)) {
            modelo = gru.cargarDatosNotasParaJTable();
            cargarDatos();
            mostrarMensaje("Se eliminó con éxito");
        }
        else{
            mostrarMensaje("No se eliminó, probablemente no existe el id");
        }
    }//GEN-LAST:event_jButton3_DEL_ActionPerformed

    private void jButton2_ADD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ADD_ActionPerformed
        // TODO add your handling code here:
        String sideNota = jTextField4_IDNOTA_.getText();
        int idNota = Integer.parseInt(sideNota);
        String sidest = jTextField1_IdEst_.getText();
        int idEst = Integer.parseInt(sidest);
        String stipo = jTextField6_TIPO_.getText();
        char tipo = stipo.charAt(0);
        String svalor = jTextField7_VALOR_.getText();
        double valor = Double.parseDouble(svalor);
        String sporcentaje = jTextField8_PORCENTAJE_.getText();
        double porcentaje = Double.parseDouble(sporcentaje);
        String scorte = jTextField9_CORTE_.getText();
        int corte = Integer.parseInt(scorte);
        
        Nota add = new Nota(idNota,tipo,valor,porcentaje,idEst,corte);
        gru.addNota(add);
        moverAlaVentana(add);
        mostrarMensaje("La nota con codigo "+idNota+" ha sido añadido con exito");
    }//GEN-LAST:event_jButton2_ADD_ActionPerformed

    private void jButton5_MOD_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_MOD_ActionPerformed
        // TODO add your handling code here:
        cargarDatos();
        int idNota = 0;
        String sidNota = "";
        sidNota = jTextField4_IDNOTA_.getText();
        idNota = Integer.parseInt(sidNota);
        
        if ((gru.buscarNota(idNota)==null)) {
            mostrarMensaje("La nota con el id "+idNota+" no existe");
            return;
        }
        double valor = 0.0;
        double porcentaje = 0.0;
        int idEst = 0;
        int corte = 0;
        char tipo = ' ';
        
        String stipo = jTextField6_TIPO_.getText();
        tipo = stipo.charAt(0);
        String svalor = jTextField7_VALOR_.getText();
        valor = Double.parseDouble(svalor);
        String sporcentaje = jTextField8_PORCENTAJE_.getText();
        porcentaje = Double.parseDouble(sporcentaje);
        String scorte = jTextField9_CORTE_.getText();
        corte = Integer.parseInt(scorte);
        
        Nota nvox = new Nota(idNota,tipo,valor,porcentaje,idEst,corte);
        if (gru.modificarNota(nvox))
            
        mostrarMensaje("La nota con codigo "+idNota+" ha sido modificada con exito");
        else
            mostrarMensaje("La nota con codigo "+idNota+" no existe");
    }//GEN-LAST:event_jButton5_MOD_ActionPerformed

    private void jTextField4_IDNOTA_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4_IDNOTA_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_IDNOTA_ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jLabel15MouseClicked
    public void moverCalculos(){
        jTextField4_porcentaje2_.setText(Double.toString(Calculos.porcentaje));
        jTextField1_promedio_.setText(Double.toString(Calculos.promedio));
        jTextField5_cantidadQyT_.setText(Integer.toString(Calculos.nroQyT));
        jTextField3_Definitiva_.setText(Double.toString(Calculos.definitivaCorte));
    }
    public void mostrarMensaje(String m){
        javax.swing.JOptionPane.showMessageDialog(this,m);
    }
    
    public void cargarFoto(String ruta, String foto){
        //String dirRutaFoto = ruta + foto + ".JPG"
        /*
        String dirRutaFoto = ruta + foto + ".JPG";
        javax.swing.ImageIcon iconfoto = new javax.swing.ImageIcon(dirRutaFoto);
        // jlabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/100.JPG")));
        if (iconfoto.getImageLoadStatus() == java.awt.MediaTracker.COMPLETE) {
            jLabel2.setText("");
            jLabel2.setIcon(iconfoto); //Se pone en el jlabel
        }
        else{
            dirRutaFoto = ruta+"nofoto.JPG";
            iconfoto = new javax.swing.ImageIcon(dirRutaFoto);
            jLabel2.setText("");
            jLabel2.setIcon(iconfoto); //Se pone en el jlabel 
        }
        */
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NotasGUI dialog = new NotasGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_BUSCAR_;
    private javax.swing.JButton jButton2_ADD_;
    private javax.swing.JButton jButton3_DEL_;
    private javax.swing.JButton jButton4_BuscarPorIdNota_;
    private javax.swing.JButton jButton5_MOD_;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_IdEst_;
    private javax.swing.JTextField jTextField1_promedio_;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField2_APELLIDO_;
    private javax.swing.JTextField jTextField3_Definitiva_;
    private javax.swing.JTextField jTextField3_NOMBRE_;
    private javax.swing.JTextField jTextField4_IDNOTA_;
    private javax.swing.JTextField jTextField4_porcentaje2_;
    private javax.swing.JTextField jTextField5_IDEST_;
    private javax.swing.JTextField jTextField5_cantidadQyT_;
    private javax.swing.JTextField jTextField6_TIPO_;
    private javax.swing.JTextField jTextField7_VALOR_;
    private javax.swing.JTextField jTextField8_PORCENTAJE_;
    private javax.swing.JTextField jTextField9_CORTE_;
    // End of variables declaration//GEN-END:variables
}
